/* SPDX-License-Identifier: GPL-2.0 OR BSD-2-Clause */
/*
 * Copyright (c) 2018-2020, The Linux Foundation. All rights reserved.
 * Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
 */

#ifndef __DT_BINDINGS_AUDIOLITE_MAILBOX_IPCC_8797P_H
#define __DT_BINDINGS_AUDIOLITE_MAILBOX_IPCC_8797P_H

/* Signal IDs for COMPUTE_L1 protocol */
#define IPCC_COMPUTE_L1_SIGNAL_MSG	16
#define IPCC_COMPUTE_L1_SIGNAL_ACK	17
#define IPCC_COMPUTE_L1_SIGNAL_PROCESSING	18
#define IPCC_COMPUTE_L1_SIGNAL_PROCESSING_ACK	19
#define IPCC_COMPUTE_L1_SIGNAL_TUNING	20
#define IPCC_COMPUTE_L1_SIGNAL_TUNING_ACK	21
#define IPCC_COMPUTE_L1_SIGNAL_EVENT	22
#define IPCC_COMPUTE_L1_SIGNAL_EVENT_ACK	23

#define IPCC_COMPUTE_L1_ADSP0		0
#define IPCC_COMPUTE_L1_APSS_NS1	7
#define IPCC_COMPUTE_L1_ADSP1		16
#define IPCC_COMPUTE_L1_ADSP2		17

#endif //__DT_BINDINGS_AUDIOLITE_MAILBOX_IPCC_8797P_H
