dtbo-y += sa8775p_audiolite_common.dtbo
dtbo-$(CONFIG_AUDIOLITE_OVERLAY) += sa8775p_audiolite_overlay.dtbo

dtbo-y += sa8255p_audiolite_common.dtbo
dtbo-$(CONFIG_AUDIOLITE_OVERLAY) += sa8255p_audiolite_overlay.dtbo

dtbo-y += sa8797p_audiolite_common.dtbo
dtbo-$(CONFIG_AUDIOLITE_OVERLAY) += sa8797p_audiolite_overlay.dtbo

dtbo-y += sa8797p_audiolite_common-iqx.dtbo
dtbo-$(CONFIG_AUDIOLITE_OVERLAY) += sa8797p_audiolite_overlay-iqx.dtbo

always-y := $(dtb-y) $(dtbo-y)
subdir-y := $(dts-dirs)
clean-files := *.dtb *.dtbo
