# SPDX-License-Identifier: GPL-2.0
dtb-y += sa8775p_audiolite_overlay.dtbo
dtb-y += safelinux-system-cfg/sa8775p_overlay.dtbo
dtb-y += safelinux-system-cfg/sa8775p-qvp/sa8775p-qvp.dtb
dtb-y += safelinux-system-cfg/sa8770p-ride/sa8770p-ride.dtb
dtb-y += safelinux-system-cfg/sa8775p-ride-mx/sa8775p-ride-mx.dtb
dtb-y += safelinux-system-cfg/sa8650p-ride/sa8650p-ride.dtb
dtb-y += safelinux-system-cfg/sa8255p-ride/sa8255p-ride.dtb
dtb-y += safelinux-system-cfg/sa7255p-ride/sa7255p-ride.dtb

#include common target file
include $(PWD)/Makefile.common
